<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
add_filter( 'genesis_pre_get_option_site_layout', 'content_sidebar_layout_single_posts' );
function content_sidebar_layout_single_posts( $opt ) {
    $opt = 'content-sidebar'; 
    return $opt;
}



remove_action('genesis_loop', 'genesis_do_loop');

add_action('genesis_loop', 'gt_custom_loop');
function gt_custom_loop() {

	if (have_posts()) :
		while (have_posts()) : the_post();
			?>
			<header class="entry-header">
				<h1 class="entry-title" itemprop="headline"><?php echo get_the_title();?></h1>
			</header>
			<div class="img-consejos">
			<?php
				the_post_thumbnail( 'full' );
			?>
			</div>

			<div class="content-consejos">

			<p ><span class="entry-date"><?php echo get_the_date('j'). ' de '.get_the_date('F'). ' de '. get_the_date('Y'); ?></span> | Consejos</p>
			<?php
				the_content();


			?>
			<div class="addthis_toolbox addthis_default_style addthis_32x32_style share">
			  <a class="addthis_counter_facebook"></a>
			  <a class="addthis_counter_twitter"></a>
			  <a class="addthis_counter_google"></a>
			  <a class="addthis_counter_linkedin"></a>
			</div>
			

			<!--  <div class="share">
			    <ul class="share_addthis_custom share-desktop" id="share_addthis_custom" data-title="Make This One Change to Reduce Social Media Anxiety" data-url="" data-content="" data-caption="">
			        <li><a href="javascript:void(0);" addthis:url="<?php echo get_the_permalink();?>" addthis:title="<?php echo get_the_title();?>" class="addthis_button_facebook st_facebook_large at300b" style="text-decoration:none;" title="Facebook"><span class="stLarge"><img src="//propiedades.ruvix.com/wp-content/uploads/2017/06/facebook.png"></span></a></li>
			        <li><a addthis:url="" addthis:title="<?php echo get_the_title();?>" tw:text="" class="addthis_button_twitter st_twitter_large at300b" style="text-decoration:none;" title="Twitter" href="#"><span class="stLarge"><img src="//propiedades.ruvix.com/wp-content/uploads/2017/06/twitter.png"></span></a></li>
			        <li>
			            <a href="https://plus.google.com/share?url=<?php echo get_the_permalink();?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><img src="//propiedades.ruvix.com/wp-content/uploads/2017/06/google.png" alt="Share on Google+"></a>
			        </li>
			        <li>
			            <a class="addthis_button_linkedin at300b" addthis:url="" addthis:title="<?php echo get_the_title();?>" target="_blank" title="LinkedIn" href="#"><img src="//propiedades.ruvix.com/wp-content/uploads/2017/06/linkedin.png"  border="0" alt="Linkedin"></a>
			        </li>
			    </ul>
			</div>  -->
			</div>
			<?php
		endwhile;
	endif;

	
}

add_action('genesis_before_footer', function() {
	echo '<div class="wrap">';
	dynamic_sidebar( 'after-entry' );
	echo '</div>';
}, 0);

genesis();