<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.


remove_action( 'genesis_entry_header', 'genesis_entry_header_markup_open', 5 );
remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );
remove_action( 'genesis_entry_header', 'genesis_entry_header_markup_close', 15 );

remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_open', 5 );
remove_action( 'genesis_entry_footer', 'genesis_post_meta' );
remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_close', 15 );



remove_action( 'genesis_loop', 'genesis_do_loop' );

add_action( 'genesis_before_loop', 'single_loop_custom' );
function single_loop_custom(){

	while ( have_posts() ) : the_post();

		echo '<h2>'.get_the_title().'</h2>';
		echo '<div class="one-half first">';
			$thumb_id = get_post_thumbnail_id();
			$thumb_url = wp_get_attachment_image_src($thumb_id, 'full', true);
			echo '<img src="'.$thumb_url[0].'"/>';
		echo '</div>';
		echo '<div class="one-half">';
			echo '<h4>Descripción</h4>';
			echo '<div class="one-half first"><strong>Estado: </strong></div><div class="one-half">'.get_field('estado').'</div>';
			echo '<div class="one-half first"><strong>Precio: </strong></div><div class="one-half">'.get_field('precio').'</div>';
			if(get_field('descripcion_corta'))
			echo '<div class="one-half first"><strong>Descripción Corta: </strong></div><div class="one-half">'.get_field('descripcion_corta').'</div>';
		echo '</div>';
		echo '<p style="clear: both;"><br>'.get_the_content().'</p>';
	endwhile;	
	dynamic_sidebar( 'after-entry' );	
	
}	




genesis();
